### ISSUE TITLE
URL Shortener

### ISSUE THREAD

**Issue by prodigyinfotech** [Prodigy-InfoTech/Software-Developement-Projects#10]
Develop a web-based URL shortening service that takes long URLs and converts them into shorter, more manageable links. Users can then share these shortened links, and when others click on them, they are redirected to the original long URL.

**Comment by prabincankod** [comment]
i can do this. can you assign this to me.

**Comment by prodigyinfotech** [comment]
Assigned

**Comment by prabincankod** [comment]
@prodigyinfotech  merge this #14

**Comment by prodigyinfotech** [comment]
Hey, @prabincankod! This project has been moved to the Web Development repository. So, please raise a PR there.
Here, is the link: https://github.com/Prodigy-InfoTech/Web-Development-Projects/issues/44
